# Generated by Django 4.2.27 on 2025-12-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='الشركة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة المكرمة'), ('medina', 'المدينة المنورة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('taif', 'الطائف'), ('tabuk', 'تبوك'), ('other', 'أخرى')], max_length=50, verbose_name='المدينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط التقديم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فرصة عمل',
                'verbose_name_plural': 'فرص العمل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(verbose_name='تاريخ الإفراج')),
                ('end_of_followup_date', models.DateField(verbose_name='تاريخ انتهاء المتابعة')),
                ('risk_level', models.CharField(choices=[('green', '🟢 أخضر - Green'), ('yellow', '🟡 أصفر - Yellow'), ('red', '🔴 أحمر - Red')], default='green', max_length=10, verbose_name='مستوى الخطورة')),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة المكرمة'), ('medina', 'المدينة المنورة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('taif', 'الطائف'), ('tabuk', 'تبوك'), ('other', 'أخرى')], default='riyadh', max_length=50, verbose_name='المدينة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ملف الإفراج',
                'verbose_name_plural': 'ملفات الإفراج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='رقم الهوية الوطنية')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('beneficiary', 'مستفيد - Beneficiary'), ('case_worker', 'أخصائي - Case Worker'), ('admin', 'مدير - Admin')], default='beneficiary', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الجوال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('job', '💼 دعم وظيفي - Job Support'), ('social', '🤝 دعم اجتماعي - Social Support'), ('psychological', '🧠 دعم نفسي - Psychological Support'), ('housing', '🏠 دعم سكني - Housing Support'), ('financial', '💰 دعم مالي - Financial Support')], max_length=20, verbose_name='نوع التذكرة')),
                ('status', models.CharField(choices=[('open', 'مفتوح - Open'), ('in_progress', 'قيد المعالجة - In Progress'), ('resolved', 'تم الحل - Resolved'), ('closed', 'مغلق - Closed')], default='open', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='إنشاء تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='core.user', verbose_name='أنشئ بواسطة')),
                ('release_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.releaseprofile', verbose_name='ملف الإفراج')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='releaseprofile',
            name='assigned_case_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'case_worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to='core.user', verbose_name='الأخصائي المسؤول'),
        ),
        migrations.AddField(
            model_name='releaseprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_profile', to='core.user', verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='الرابط')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveIntegerField(verbose_name='رقم الشهر')),
                ('housing_status', models.CharField(choices=[('stable', 'مستقر - Stable'), ('temporary', 'مؤقت - Temporary'), ('with_family', 'مع العائلة - With Family'), ('homeless', 'بدون مأوى - Homeless')], max_length=20, verbose_name='حالة السكن')),
                ('job_status', models.CharField(choices=[('employed', 'موظف - Employed'), ('self_employed', 'عمل حر - Self Employed'), ('searching', 'يبحث عن عمل - Searching'), ('unemployed', 'عاطل - Unemployed'), ('training', 'في تدريب - In Training')], max_length=20, verbose_name='حالة العمل')),
                ('mental_state', models.CharField(choices=[('good', 'جيد - Good'), ('moderate', 'متوسط - Moderate'), ('stressed', 'متوتر - Stressed'), ('bad', 'سيء - Bad')], max_length=20, verbose_name='الحالة النفسية')),
                ('family_status', models.CharField(choices=[('supportive', 'داعمة - Supportive'), ('neutral', 'محايدة - Neutral'), ('problematic', 'مشكلات - Problematic'), ('no_contact', 'لا تواصل - No Contact')], max_length=20, verbose_name='حالة العائلة')),
                ('free_text_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.releaseprofile', verbose_name='ملف الإفراج')),
            ],
            options={
                'verbose_name': 'متابعة شهرية',
                'verbose_name_plural': 'المتابعات الشهرية',
                'ordering': ['-month_index'],
                'unique_together': {('release_profile', 'month_index')},
            },
        ),
    ]
